services:
  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:80" #Forwards the port from the host to the container
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - ./backend/todos.json:/app/todos.json
    networks:
      - app-network
    restart: always

# Creates a virtual network app-network with the bridge driver.
# Containers can communicate by name, for example, the backend is available to the frontend as http://backend:3000 .
networks:
  app-network:
    driver: bridge
